# Generated by Django 6.0.2 on 2026-02-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circleevents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='postcode',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
