# Generated by Django 6.0.2 on 2026-02-19 18:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circleevents', '0004_alter_profile_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='event image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile image'),
        ),
    ]
