# Generated by Django 6.0.2 on 2026-02-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circleevents', '0005_alter_event_event_img_alter_profile_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='admin_comment',
            field=models.TextField(blank=True),
        ),
    ]
