# Generated by Django 6.0.2 on 2026-02-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circleevents', '0006_event_admin_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='moderation_notified',
            field=models.BooleanField(default=False),
        ),
    ]
